- name: Create vault namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ vault_namespace }}'

- name: Deploy vault
  helm:
    name: vault
    namespace: '{{ vault_namespace }}'
    chart_repo_url: https://helm.releases.hashicorp.com
    chart_ref: vault
    chart_version: '{{ vault_chart_version }}'
    values:
      server:
        dev:
          enabled: true
        image:
          repository: '{{ vault_image }}'
          tag: '{{ vault_tag }}'
    wait: yes
